export const FETCH_TOP_SALES_ERROR = 'FETCH_TOP_SALES_ERROR';
export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';

export const FETCH_CATALOG_CATEGORIES_ERROR = 'FETCH_CATALOG_CATEGORIES_ERROR';
export const FETCH_CATALOG_CATEGORIES_REQUEST = 'FETCH_CATALOG_CATEGORIES_REQUEST';
export const FETCH_CATALOG_CATEGORIES_SUCCESS = 'FETCH_CATALOG_CATEGORIES_SUCCESS';

export const FETCH_CATALOG_ITEMS_ERROR = 'FETCH_CATALOG_ITEMS_ERROR';
export const FETCH_CATALOG_ITEMS_REQUEST = 'FETCH_CATALOG_ITEMS_REQUEST';
export const FETCH_CATALOG_ITEMS_SUCCESS = 'FETCH_CATALOG_ITEMS_SUCCESS';

export const SET_MORE_BUTTON_VISIBILITY = 'SET_MORE_BUTTON_VISIBILITY';
export const SET_SELECTED_CATEGORY_ID = 'SET_SELECTED_CATEGORY_ID';
